RESTORE DATABASE [{0}] 
FROM 
 {1} 
WITH FILE = 1, 
MOVE N'{2}' TO N'{3}',  
MOVE N'{2}_log' TO N'{4}',  
NOUNLOAD,  
REPLACE,  
STATS = 5;

CREATE LOGIN [{5}] 
WITH 
PASSWORD=N'{6}', 
DEFAULT_DATABASE=[{0}], 
CHECK_EXPIRATION=OFF, 
CHECK_POLICY=OFF;

CREATE USER [{5}] FOR LOGIN [{5}];
ALTER ROLE [db_datareader] ADD MEMBER [{5}];
ALTER ROLE [db_datawriter] ADD MEMBER [{5}];
ALTER ROLE [db_ddladmin] ADD MEMBER [{5}]
